# --- General ---
[general]
import = [
    "~/.config/alacritty/themes/tokyo_night.toml"
]

# --- Window ---
[window]
startup_mode = "Maximized"
padding = { x = 6, y = 6 }
decorations = "none"
opacity = 0.8

# --- Font ---
[font]
size = 14.0

normal = { family = "Mononoki Nerd Font Mono", style = "Regular" }
bold = { family = "Mononoki Nerd Font Mono", style = "Bold" }
italic = { family = "Mononoki Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Mononoki Nerd Font Mono", style = "Bold Italic" }

offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

# --- Cursor ---
[cursor]
vi_mode_style = "Block"

[cursor.style]
shape = "Beam"
blinking = "On"

# --- Scrolling ---
[scrolling]
history = 10000
multiplier = 3

# --- Mouse ---
[mouse]
hide_when_typing = true
